(()=>{
const PIN='yk-admin-pin-v1', KNOW='yk-admin-knowledge-v1', LAND='yk-v3-clean', CHAT='yk-yar-chat-v4';
const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const read=(k,d)=>{try{return JSON.parse(localStorage.getItem(k)||JSON.stringify(d))}catch{return d}};
const write=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
async function hash(v){const b=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(v));return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('')}
function lands(){const s=read(LAND,{});return Array.isArray(s.lands)?s.lands:[]}
function tx(){const s=read(LAND,{});return Array.isArray(s.transactions)?s.transactions:[]}
function chats(){const x=read(CHAT,[]);return Array.isArray(x)?x:[]}
function knowledge(){return read(KNOW,[])}
function fmt(n){return Number(n||0).toLocaleString('fa-IR')}
function refresh(){const ls=lands(), t=tx(); const area=ls.reduce((a,x)=>a+Number(x.area||x.hectare||0),0); const income=t.filter(x=>x.type==='income').reduce((a,x)=>a+Number(x.amount||0),0); const cost=t.filter(x=>x.type==='expense').reduce((a,x)=>a+Number(x.amount||0),0); $('#landCount').textContent=fmt(ls.length);$('#areaTotal').textContent=fmt(area);$('#questionCount').textContent=fmt(chats().length);$('#profit').textContent=fmt(income-cost);$('#status').textContent=`این نسخه روی همین دستگاه کار می‌کند. ${ls.length} زمین، ${chats().length} پیام و ${knowledge().length} دانش مدیریتی ذخیره شده است.`; renderLands();renderKnowledge();renderChat()}
function renderLands(){const el=$('#landsList'),ls=lands();el.innerHTML=ls.length?ls.map((l,i)=>`<div class="item"><b>${esc(l.name||`زمین ${i+1}`)}</b><small>مساحت: ${esc(l.area??l.hectare??'ثبت نشده')} | محصول: ${esc(l.crop||l.product||'ثبت نشده')}</small><small>خاک: ${esc(l.soil||'—')} | آبیاری: ${esc(l.irrigation||'—')}</small></div>`).join(''):'<p class="note">هنوز زمینی ثبت نشده است.</p>'}
function renderKnowledge(){const el=$('#knowledgeList'),ks=knowledge();el.innerHTML=ks.length?ks.map((k,i)=>`<div class="item"><b>${esc(k.title)}</b><small>کلیدواژه: ${esc((k.keywords||[]).join('، '))}</small><small>${esc(k.answer)}</small><button class="danger" data-del="${i}">حذف</button></div>`).join(''):'<p class="note">دانش مدیریتی افزوده نشده است.</p>';el.querySelectorAll('[data-del]').forEach(b=>b.onclick=()=>{const a=knowledge();a.splice(+b.dataset.del,1);write(KNOW,a);refresh()})}
function renderChat(){const el=$('#chatList'),cs=chats().slice(-80).reverse();el.innerHTML=cs.length?cs.map((x,i)=>`<div class="item"><b>${esc(x.role||'پیام')}</b><small>${esc(x.content||x.text||JSON.stringify(x))}</small></div>`).join(''):'<p class="note">تاریخچه‌ای ذخیره نشده است.</p>'}
function tabs(){document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>{document.querySelectorAll('nav button').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelectorAll('.tab').forEach(x=>x.hidden=x.id!==b.dataset.tab)})}
function setup(){ $('#app').hidden=false;$('#login').remove();tabs();refresh();$('#refresh').onclick=refresh;$('#openApp').onclick=()=>location.href='./';$('#knowledgeForm').onsubmit=e=>{e.preventDefault();const a=knowledge();a.push({title:$('#ktitle').value,keywords:$('#kkeys').value.split(/[,،]/).map(x=>x.trim()).filter(Boolean),answer:$('#kanswer').value,tags:$('#ktags').value.split(/[,،]/).map(x=>x.trim()).filter(Boolean),createdAt:new Date().toISOString()});write(KNOW,a);e.target.reset();refresh();alert('دانش ذخیره شد و در موتور آفلاین قابل استفاده است.')};$('#export').onclick=()=>{const data={version:1,createdAt:new Date().toISOString(),knowledge:knowledge(),lands:lands(),transactions:tx(),chat:chats()};const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='yar-keshavarz-admin-backup.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)};$('#import').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{const d=JSON.parse(await f.text());if(Array.isArray(d.knowledge))write(KNOW,d.knowledge);if(Array.isArray(d.lands))write(LAND,{...read(LAND,{}),lands:d.lands});if(Array.isArray(d.chat))write(CHAT,d.chat);refresh();alert('پشتیبان وارد شد.')}catch{alert('فایل پشتیبان معتبر نیست.')}};$('#clearKnowledge').onclick=()=>{if(confirm('همه دانش‌های مدیریتی حذف شود؟')){localStorage.removeItem(KNOW);refresh()}};$('#changePin').onclick=async()=>{const old=prompt('رمز فعلی را وارد کنید');if(!old)return;if(await hash(old)!==localStorage.getItem(PIN))return alert('رمز فعلی نادرست است.');const n=prompt('رمز جدید حداقل ۴ رقم/حرف');if(n&&n.length>=4)localStorage.setItem(PIN,await hash(n));alert('رمز تغییر کرد.')};$('#logout').onclick=()=>{sessionStorage.removeItem('yk-admin-auth');location.reload()}}
async function boot(){const stored=localStorage.getItem(PIN);if(!stored){$('#loginHint').textContent='برای اولین ورود یک رمز حداقل ۴ رقمی بسازید.';$('#pin2').hidden=false}else $('#pin2').hidden=true;$('#loginForm').onsubmit=async e=>{e.preventDefault();const p=$('#pin').value;if(!stored){if(p!==$('#pin2').value||p.length<4)return $('#loginError').textContent='دو رمز یکسان نیستند یا کوتاه است.';localStorage.setItem(PIN,await hash(p));sessionStorage.setItem('yk-admin-auth','1');setup()}else{if(await hash(p)!==stored)return $('#loginError').textContent='رمز نادرست است.';sessionStorage.setItem('yk-admin-auth','1');setup()}};if(sessionStorage.getItem('yk-admin-auth')==='1')setup()}
boot();
})();
