// YarKeshavarz Weather Advisor V1
// Uses Open-Meteo geocoding + forecast when internet is available.
// Keeps the last successful forecast in localStorage for offline fallback.
const GEO='https://geocoding-api.open-meteo.com/v1/search';
const WX='https://api.open-meteo.com/v1/forecast';
const CACHE_KEY='yk-weather-cache-v1';
const TTL=30*60*1000;
function norm(s=''){return String(s).toLowerCase().replace(/[يى]/g,'ی').replace(/ك/g,'ک').replace(/\u200c/g,' ').replace(/\s+/g,' ').trim()}
function label(code){if(code===0)return'صاف';if([1,2,3].includes(code))return'نیمه‌ابری تا ابری';if([45,48].includes(code))return'مه‌آلود';if([51,53,55,56,57].includes(code))return'نم‌نم باران';if([61,63,65,66,67,80,81,82].includes(code))return'بارانی';if([71,73,75,77,85,86].includes(code))return'برفی';if([95,96,99].includes(code))return'رعدوبرق';return'نامشخص'}
function readCache(){try{return JSON.parse(localStorage.getItem(CACHE_KEY)||'null')}catch{return null}}
function saveCache(x){try{localStorage.setItem(CACHE_KEY,JSON.stringify(x))}catch{}}
async function geocode(region){const q=String(region||'').trim();if(!q)return null;const u=GEO+'?name='+encodeURIComponent(q)+'&count=1&language=fa&format=json';const r=await fetch(u);if(!r.ok)throw new Error('geocoding');const d=await r.json();return d.results?.[0]||null}
async function forecast(lat,lon){const params=new URLSearchParams({latitude:lat,longitude:lon,timezone:'auto',forecast_days:'7',daily:'weather_code,temperature_2m_max,temperature_2m_min,precipitation_probability_max,precipitation_sum,wind_speed_10m_max,et0_fao_evapotranspiration'});const r=await fetch(WX+'?'+params);if(!r.ok)throw new Error('forecast');return await r.json()}
function summarize(d,place,land){const x=d.daily||{},days=x.time||[];const rows=days.slice(0,7).map((date,i)=>({date,tmax:x.temperature_2m_max?.[i],tmin:x.temperature_2m_min?.[i],rain:x.precipitation_probability_max?.[i]??0,mm:x.precipitation_sum?.[i]??0,wind:x.wind_speed_10m_max?.[i]??0,et0:x.et0_fao_evapotranspiration?.[i]??0,code:x.weather_code?.[i]}));const rain=Math.max(...rows.map(x=>Number(x.rain)||0));const rainMm=rows.reduce((s,x)=>s+(Number(x.mm)||0),0);const hot=Math.max(...rows.map(x=>Number(x.tmax)||-99));const cold=Math.min(...rows.map(x=>Number(x.tmin)||99));const wind=Math.max(...rows.map(x=>Number(x.wind)||0));let notes=[];if(rain>=60||rainMm>=10)notes.push('🌧️ احتمال بارش قابل‌توجه وجود دارد؛ قبل از آبیاری و عملیات مزرعه بارش را بررسی کن.');if(hot>=35)notes.push('🔥 چند روز گرم پیش‌بینی شده؛ تنش گرمایی و نیاز آبی محصول را پایش کن.');if(cold<=2)notes.push('🥶 دمای کم پیش‌بینی شده؛ برای محصولات حساس به سرما احتیاط کن.');if(wind>=35)notes.push('🌬️ باد نسبتاً شدید پیش‌بینی شده؛ عملیات محلول‌پاشی/سم‌پاشی را با شرایط باد تطبیق بده.');if(!notes.length)notes.push('✅ در این پیش‌بینی، هشدار عمومی شدیدی برای بارش، گرما، سرما یا باد دیده نشد.');const first=rows[0];return {text:`\n\n🌦️ پیش‌بینی ۷ روزه زمین «${land?.name||'انتخاب‌شده'}»\n📍 ${place}\n🌡️ امروز: ${first?.tmin??'-'} تا ${first?.tmax??'-'}°C | ${label(first?.code)}\n🌧️ احتمال بیشینه بارش: ${rain}% | مجموع بارش ۷ روز: ${rainMm.toFixed(1)} میلی‌متر\n💨 بیشینه باد: ${wind} km/h | تبخیر-تعرق مرجع ۷ روز: ${rows.reduce((s,x)=>s+(Number(x.et0)||0),0).toFixed(1)} mm\n${notes.join('\n')}`,data:{place,rows,notes,updatedAt:Date.now()}}}
export async function getWeatherAdvice(context={}){const l=context?.l||context?.land||context||{};const region=String(l.region||'').trim();if(!region)return null;try{const g=await geocode(region);if(!g)throw new Error('location');const d=await forecast(g.latitude,g.longitude);const out=summarize(d,`${g.name}${g.admin1?', '+g.admin1:''}${g.country?', '+g.country:''}`,l);saveCache({region,out,at:Date.now()});return out}catch(e){const c=readCache();if(c&&norm(c.region)===norm(region))return c.out;return null}}
export default getWeatherAdvice;
